#!/usr/bin/env zsh
#          _
#  _______| |__   ___ _ ____   __
# |_  / __| '_ \ / _ \ '_ \ \ / /
#  / /\__ \ | | |  __/ | | \ V /
# /___|___/_| |_|\___|_| |_|\_/
#
# Basic Environment for zsh with debugging provision
# h@h-lo.me 20190110 115942 -0800 PST 1547150382 d(-_- )b...

[[ -f "${HOME}/.debug" ]] && setopt xtrace sourcetrace
   # this file gets deleted on completion of .login for
   # interactive shells

[[ -z ${ZDOTDIR}  ]] &&  typeset -x ZDOTDIR=$HOME/.zconf

typeset os=$(uname -o)

case os in
  FreeBSD)
    typeset freebsd=true ;;
  Linux)
    typeset linux=true ;;
  Darwin)
    typeset mac=true ;;
  Android)
    typeset termux=true ;;
  * )
    false ;;
esac

[[ $termux ]] && {
  typeset -x TZ=$(getprop persist.sys.timezone)
  typeset -x TERMUXPREFIX=/data/data/com.termux/files/usr
  typeset -x GCPSDK=$TERMUXPREFIX/google-cloud-sdk
  typeset -x USRLOCAL=$TERMUXPREFIX/local
}

[[ $freebsd || $mac ]] && {
  typeset -x USRLOCAL=/usr/local
  typeset -x GCPSDK=$USRLOCAL/google-cloud-sdk
}

[[ $linux ]] && {
  typeset -x USRLOCAL=/usr/local
  typeset -x GCPSDK=/opt/google-cloud-sdk
  typeset -x TZ="/usr/share/zoneinfo/America/Tijuana"
}
#bypasses system configs, full of nonsense

unsetopt global_rcs

# Ensure that a non-login, non-interactive shell has a defined environment.
# Sorin Ionescu <sorin.ionescu@gmail.com>
[[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]] && source "${ZDOTDIR:-$HOME}/.zprofile"

#  vim: set ft=zsh sw=2 tw=0 fdm=manual et :
