# This tmux statusbar config was created by tmuxline.vim
# on Mon, 02 Mar 2015

set -g status-bg "colour61"
set -g message-command-fg "colour250"
set -g status-justify "left"
set -g status-left-length "100"
set -g status "on"
set -g pane-active-border-fg "colour125"
set -g message-bg "colour241"
set -g status-right-length "100"
set -g status-right-attr "none"
set -g message-fg "colour250"
set -g message-command-bg "colour241"
set -g status-attr "none"
set -g status-utf8 "on"
set -g pane-border-fg "colour241"
set -g status-left-attr "none"
setw -g window-status-fg "colour240"
setw -g window-status-attr "none"
setw -g window-status-activity-bg "colour61"
setw -g window-status-activity-attr "none"
setw -g window-status-activity-fg "colour125"
setw -g window-status-separator ""
setw -g window-status-bg "colour61"
set -g status-left "#[fg=colour250,bg=colour125,bold] #S:#I.#P•#W #[fg=colour125,bg=colour241,nobold,nounderscore,noitalics]#[fg=colour230,bg=colour241] #W #[fg=colour241,bg=colour61,nobold,nounderscore,noitalics]#[fg=colour240,bg=colour61] #H #[fg=colour61,bg=colour61,nobold,nounderscore,noitalics]"
set -g status-right "#[fg=colour61,bg=colour61,nobold,nounderscore,noitalics]#[fg=colour240,bg=colour61] %a #[fg=colour241,bg=colour61,nobold,nounderscore,noitalics]#[fg=colour250,bg=colour241 #W %R #[fg=colour125,bg=colour241,nobold,nounderscore,noitalics]#[fg=colour230,bg=colour125] #h "
setw -g window-status-format "#[fg=colour61,bg=colour61,nobold,nounderscore,noitalics]#[default] #F#I•#W #[fg=colour61,bg=colour61,nobold,nounderscore,noitalics]"
setw -g window-status-current-format "#[fg=colour61,bg=colour241,nobold,nounderscore,noitalics]#[fg=colour250,bg=colour241] #F#I•#W #[fg=colour241,bg=colour61,nobold,nounderscore,noitalics]"
