#!/usr/bin/env zsh
autoload -Uz zrecompile

# call AFTER zcompile, so .zwc caches replace dirs in fpath
      for ((i=1; i <= $#fpath; ++i)); do
        dir=$fpath[i]
        local zwc=${dir:t}.zwc
        if [[ $dir == (.|..) || $dir == (.|..)/* ]]; then
          continue
        fi
        local files=($dir/*(N-.))
        if [[ -w $dir:h && -n $files ]]; then
          files=(${${(M)files%/*/*}#/})
          if ( cd $dir:h &&
               zrecompile -p -U -z $zwc $files ); then
            fpath[i]=$fpath[i].zwc
          fi
        fi
      done



#  vim: set ft=zsh sw=4 tw=0 fdm=marker foldlevel=0 et :
