#!/usr/bin/env zsh
#   __            _
#  / _| ___  _ __| |_ _   _ _ __   ___
# | |_ / _ \| '__| __| | | | '_ \ / _ \
# |  _| (_) | |  | |_| |_| | | | |  __/
# |_|  \___/|_|   \__|\__,_|_| |_|\___|
#
#  h@h-lo.me 20180214 005157 -0800 PST 1518598317 d(-_- )b...
#
# a wrapper for the fortune command, it just adds some
# padding around so it looks nicer. Might add syntax highlighting
#
typeset -a le_fortune
typeset -i curline=0
for line in $(command fortune "${@}" )
  le_fortune += ( $line )
printf "\n\n"
for line in $le_fortune
  if (( $curline == $#le_fortune )); then
    print -P "%F{$paint} $line%f"
  else 
    printf "   %s\n" $line
  fi
  (( curline+= 1 ))
  printf "\n\n"
#
#  vim: set ft=zsh sw=2 tw=0 fdm=manual et :
