#!/usr/bin/env zsh

#  __     _
# / _| __| |_   _ _ __   ___  ___  __      ___ __ __ _ _ __  _ __   ___ _ __
#| |_ / _` | | | | '_ \ / _ \/ __| \ \ /\ / / '__/ _` | '_ \| '_ \ / _ \ '__|
#|  _| (_| | |_| | |_) |  __/\__ \  \ V  V /| | | (_| | |_) | |_) |  __/ |
#|_|  \__,_|\__,_| .__/ \___||___/   \_/\_/ |_|  \__,_| .__/| .__/ \___|_|
#                |_|                                  |_|   |_|
#
local function print_help () {
  =cat <<-EndOfHelp
	${0:t}: a function wrapper for $commands[$0]

	  usage: ${0:t} [wrapper-options] -- [{$0:t}-options] path [..path [..path] ..]

	    NOTE: first path is required. so is the option delimiter '--'
	    as some wrapper opions overlap original functions

	  options:

	EndOfHelp

  for o in $shortopts
    print -f "  $"

}


[[ $+commands[$0:t] ]] && {
  zparseopts -DMKEA opts d=shortopts -delete=d  \
                         o=shortopts -keep-older=o \
                         n=shortopts -keep-newer=n \
                         s=shortopts -summarize=s \
                         h=shortopts -help=h


zshall
} || return

#  vim: set ft=zsh sw=2 ts=2 sts=2 tw=0 fdm=manual et :
