#!/usr/bin/env zsh
#  _     _     _           _ _
# | |___| |__ (_)_ __   __| (_)_ __   __ _ ___
# | / __| '_ \| | '_ \ / _` | | '_ \ / _` / __|
# | \__ \ |_) | | | | | (_| | | | | | (_| \__ \
# |_|___/_.__/|_|_| |_|\__,_|_|_| |_|\__, |___/
#                                    |___/
#  h@h-lo.me 20180212 195431 -0800 PST 1518494071 d(-_- )b...
#  h@h-lo.me 20181204 023821 +0000 GMT 1543891101 d(-_- )b... 
for  map in $(bindkey -l )
do
  bindkey -M "$map"|
  while read binding widget
  do
    if [[ ! -z ${map:s:emacs::} ]]; then 
      print -v m -P "%F{magenta}$map%f"
      print -v b -P "%F{yellow}${(V)binding//\"/ }%f"
      if [[ ! -z ${widget:s:self-insert::} ]]; then
        print -v w -P "%F{green}${widget}%f" &>| -
        printf "%20s: %20s:%s\n" $m ${(qqq)b} $w
      fi
    fi
  done
done
#  vim: set ft=zsh sw=2 tw=0 fdm=manual et :
