#!/usr/bin/env zsh
#  _     _     _           _ _
# | |___| |__ (_)_ __   __| (_)_ __   __ _ ___
# | / __| '_ \| | '_ \ / _` | | '_ \ / _` / __|
# | \__ \ |_) | | | | | (_| | | | | | (_| \__ \
# |_|___/_.__/|_|_| |_|\__,_|_|_| |_|\__, |___/
#                                    |___/
#  h@h-lo.me 20180212 195431 -0800 PST 1518494071 d(-_- )b...

for  map in $(bindkey -l )
do
  bindkey -M "$map"|
  while read binding widget
  do
    if [[ ! -z ${map:s:emacs::} ]]; then
      m=$(print -P "%F{magenta}$map%f")
      b=$(print -P "%F{yellow}$(echo ${(V)binding}| tr -d \")%f")
      if [[ ! -z ${widget:s:self-insert::} ]]; then
        w=$(print -P "%F{green}$widget%f")
      else
        w=$(print -P "$widget")
      fi
      printf "%20s: %20s:%s\n" $m $b $w
    fi
  done
done
#  vim: set ft=zsh sw=2 tw=0 fdm=manual et :
