#!/usr/bin/env zsh
#  _     _     _           _ _
# | |___| |__ (_)_ __   __| (_)_ __   __ _ ___
# | / __| '_ \| | '_ \ / _` | | '_ \ / _` / __|
# | \__ \ |_) | | | | | (_| | | | | | (_| \__ \
# |_|___/_.__/|_|_| |_|\__,_|_|_| |_|\__, |___/
#                                    |___/
#  h@h-lo.me 20180212 195431 -0800 PST 1518494071 d(-_- )b...

for  map in $(bindkey -l )
do
  bindkey -M "$map"|
  while read binding key
 do
   echo "${(qqV)map}" "${(qqV)binding}"  "${(qV)key}" \
     | awk '!/self-insert/ &&  !/noop/ { printf " %s %s\n", $1, $2 $3 }' \
     | tr -d \"
    # if [[ ! -z ${map:s:emacs::} ]]; then
    #   m=$(print -P "%F{magenta}$map%f")
    #   b=$(print -P "%F{yellow}$(echo ${(qqV)binding}| tr -d \")%f")
    #   w=$(print -P "%F{green}$widget%f")
    #   print -f "%20s: %20s:%s\n" $m $b $w
    # fi
  done
done
#  vim: set ft=zsh.awk sw=2 tw=0 fdm=manual et :
#{ print gensub(/"(.+)"-2w"(.+)"/,"\\1-\\2","g",$3) }
