#!/usr/bin/env zsh
#
local timestamp=$(date -Iseconds)
local severity=$(argv[1])
local message=$(argv:2:$(#argv))
local logname="syslog"

# Styles for config {{{
zstyle :logging:stackdriver: enabled
zstyle :logging:level min
zstyle :logging:level max
zstyle :logging:stackdriver: LOG_NAME
zstyle :logging:stackdriver:
zstyle :logging:syslog enabled
zstyle :logging:localfile enabled
zstyle :logging:ignore (regexarray)
zstyle :logging:internal:counters tick
# }}}





[[ $+commands['gcloud'] ]] && {
    gcloud logging write $LOG_NAME "${PAYLOAD}" \
    --payload-type="json" --severity "${SEVERITY}" \
}



typeset -a  possible_severities
possible_severities=( DEFAULT DEBUG INFO NOTICE WARNING ERROR CRITICAL ALERT EMERGENCY.)
#  vim: set ft=zsh sw=4 tw=0 fdm=marker et :
