#!/usr/bin/env zsh
#           _ _                             _             _
# __  _____| (_)_ __         ___ ___  _ __ | |_ ___ _ __ | |_ ___
# \ \/ / __| | | '_ \ _____ / __/ _ \| '_ \| __/ _ \ '_ \| __/ __|
#  >  < (__| | | |_) |_____| (_| (_) | | | | ||  __/ | | | |_\__ \
# /_/\_\___|_|_| .__/       \___\___/|_| |_|\__\___|_| |_|\__|___/
#              |_|
# prints the contents of the clipboard nicely formatted
#
# h@h-lo.me 20181126 122456 -0800 PST 1543263896 d(-_- )b...
# ,
#
# this function is meant to be autoloaded by prezto and bound
# to a key using
# bindkey C-XC-? xclip xclip-contents
#
typeset -a clipoards
clipboards=( primary secondary clipboard buffer-cut )
format="%23s : %s\n"
for label in $clipboards; do
    plabel="%B${label}%b%F{red}"
    content="%f$(xclip -o -selection ${label} 2&> /dev/null)"
    print -Pf ${format} ${plabel} ${(qqq)content}
done


#  vim: set ft=zsh sw=4 tw=0 fdm=manual et :
